export class UserTestInput {
  userid: string
  dni: string
  nombres: string
  apellidos: string
  genero: string
  edad: string
  region: string
  provincia: string
  distrito: string
  direccion: string
  oficio: string
  peso: string
  talla: string
  respiracion: string
  gestante: string
  enfermedad: string
  enfermedaddetalle: string
  alergia: string
  alergiadetalle: string
  alcohol: string
  medicacion: string
  medicaciondetalle: string
  diagnostico: string
  diagnosticodetalle: string
  contactocovid: string
  fiebre: string
  tos: string
  fatiga: string
  disminucionapetito: string
  dificultadrespiracion: string
  malestargeneral: string
  malestarfechainicio: string
  otros: string
  otrosdetalle: string
  sinsintomas: string
  sensaciondeahogamiento: string
  desorientacion: string
  fiebremayordosdias: string
  dolorespechoespalda: string
  coloraciondelabios: string
  actividadesdiarias: string
  personasdeconvivencia: string
}
